repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: black
        name: Black
        description: This hook runs Black through poetry
        entry: poetry run black . --check
        language: system
        always_run: true
        pass_filenames: false
      - id: isort
        name: iSort
        description: This hook runs iSort through poetry
        entry: poetry run isort -c .
        language: system
        always_run: true
        pass_filenames: false
      - id: mypy
        name: MyPy
        description: This hook runs MypY through poetry
        entry: bash -c 'poetry run mypy --strict . | poetry run mypy-baseline filter'
        language: system
        always_run: true
        pass_filenames: false