trigger:
  tags:
    include:
      - '*'
  branches:
    include:
      - '*'

pr: none

pool: Selfhosted Azure Devops Agents

# These defaults need to be set as variables on the pipeline in the Devops webinterface
parameters:
  - name: organization
    displayName: The Azure Devops organisation URL
    type: string
    default: $(devops-organisation-url)
  - name: project
    displayName: The Azure Devops project which hosts the pipelines
    type: string
    default: $(devops-project-name)
  - name: pipelineId
    displayName: The Azure Devops pipeline ID which should be activated, this should be the Github application pipeline
    type: string
    default: $(devops-pipeline-id)
  - name: buildPipelineBranch
    displayName: The Github application pipeline branch to use, this normally should be main
    type: string
    default: refs/heads/master

jobs:
- job: TriggerPipeline
  steps:
    - script: |
        echo "$(System.AccessToken)" | az devops login --organization https://dev.azure.com/CloudCompetenceCenter/
        echo "##vso[task.setvariable variable=AZURE_DEVOPS_EXT_AZURE_DEVOPS_LOG]"true
        echo "##vso[task.setvariable variable=AZURE_DEVOPS_EXT_PATVAR]$(System.AccessToken)"
        az devops configure --defaults organization=https://dev.azure.com/CloudCompetenceCenter/ project=SIA
        az pipelines run --id 4242 --branch refs/heads/master --parameters applicationBranch=refs/heads/main
      env:
        AZURE_DEVOPS_EXT_PATVAR: $(System.AccessToken)
