services:
  meldingen:
    image: amsterdam/meldingen
    build:
      context: .
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    command: ["fastapi", "dev", "--host", "0.0.0.0", "/opt/meldingen/meldingen/main.py"]
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
      azurite:
        condition: service_healthy
    volumes:
      - ".:/opt/meldingen"

  database:
    image: postgis/postgis:16-3.4-alpine
    environment:
      POSTGRES_USER: meldingen
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meldingen
    ports:
      - "54321:5432"
    volumes:
      - "./docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "meldingen", "-U", "meldingen" ]
      interval: 10s
      timeout: 5s
      retries: 3

  keycloak:
    image: amsterdam/meldingen-keycloak
    build:
      context: docker/keycloak
    command: ["/opt/keycloak/bin/kc.sh", "start-dev", "--http-port", "8002"]
    ports:
      - "8002:8002"
    volumes:
      - "./docker/keycloak/import:/import"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

  docs:
    image: amsterdam/meldingen
    ports:
      - "8001:8000"
    volumes:
      - ".:/opt/meldingen"
    entrypoint: mkdocs serve -f /opt/meldingen/mkdocs.yml --dev-addr=0.0.0.0:8000

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    command: azurite-blob --blobHost 0.0.0.0 --blobPort 10000 --debug /var/log/azurite.log
    ports:
      - "10000:10000"
    healthcheck:
      test: nc 127.0.0.1 10000 -z
      interval: 1s
      retries: 30

  imgproxy:
    image: darthsim/imgproxy
    ports:
      - "8081:8080"
    environment:
      IMGPROXY_KEY: 313233
      IMGPROXY_SALT: 313233
      IMGPROXY_USE_ABS: "true"
      IMGPROXY_ABS_NAME: devstoreaccount1
      IMGPROXY_ABS_KEY: Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
      IMGPROXY_ABS_ENDPOINT: http://azurite:10000/devstoreaccount1
      IMGPROXY_LOG_LEVEL: debug
    healthcheck:
      test: ["CMD", "imgproxy", "health"]
