version: "3"

services:
  meldingen:
    image: amsterdam/meldingen
    build:
      context: .
    ports:
      - "8000:80"
    env_file:
      - dev.env
    volumes:
      - ".:/opt/meldingen"

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: meldingen
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meldingen
