version: "3"

services:
  meldingen:
    image: amsterdam/meldingen
    build:
      context: .
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    ports:
      - "8000:80"
    env_file:
      - dev.env
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ".:/opt/meldingen"

  database:
    image: postgis/postgis:16-3.4-alpine
    environment:
      POSTGRES_USER: meldingen
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meldingen
    ports:
      - "54321:5432"
    volumes:
      - "./docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "meldingen", "-U", "meldingen" ]
      interval: 10s
      timeout: 5s
      retries: 3

  keycloak:
    image: amsterdam/meldingen-keycloak
    build:
      context: docker/keycloak
    command: ["/opt/keycloak/bin/kc.sh", "start-dev", "--http-port", "8002"]
    ports:
      - "8002:8002"
    volumes:
      - "./docker/keycloak/import:/import"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

  docs:
    image: amsterdam/meldingen
    ports:
      - "8001:8000"
    volumes:
      - ".:/opt/meldingen"
    entrypoint: mkdocs serve -f /opt/meldingen/mkdocs.yml --dev-addr=0.0.0.0:8000
