[tool.poetry]
name = "meldingen"
version = "0.1.0"
description = "The main meldingen project which includes the framework bindings."
authors = [
  "Youri Westerman <y.westerman@amsterdam.nl>",
  "David van Buiten <d.van.buiten@amsterdam.nl>"
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
alembic = "^1.13.3"
alembic-postgresql-enum = "^1.3.0"
asgi-correlation-id = "^4.3.4"
asyncpg = "^0.30.0"
fastapi = {extras = ["standard"], version = "^0.115.2"}
geoalchemy2 = "^0.15.2"
geojson-pydantic = "^1.1.1"
maykin-json-logic-py = "^0.13.0"
meldingen-core = {git = "https://github.com/Amsterdam/meldingen-core.git", rev = "feat/list-attachments"}
mp-fsm = {git = "https://github.com/Amsterdam/mp-fsm.git"}
pydantic = {extras = ["email"], version = "^2.9.2"}
pydantic-jsonlogic = {git = "https://github.com/Amsterdam/pydantic-jsonlogic.git"}
pydantic-media-type = {git = "https://github.com/Amsterdam/pydantic-media-type.git"}
pydantic-settings = "^2.6.0"
pyjwt = {extras = ["crypto"], version = "^2.9.0"}
python-magic = "^0.4.27"
python-multipart = "^0.0.12"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.35"}
structlog = "^24.1.0"

[tool.poetry.group.dev.dependencies]
asgi-lifespan = "^2.1.0"
black = "^24.10.0"
httpx = "^0.27.2"
isort = "^5.13.2"
mkdocs-literate-nav = "^0.6.1"
mkdocs-material = "^9.5.42"
mkdocstrings = {version = "^0.26.2", extras = ["python"]}
mypy = "^1.12.1"
mypy-baseline = "^0.7.1"
pre-commit = "^4.0.0"
pytest = "^8.3.3"
pytest-alembic = "^0.11.1"
pytest-cov = "^5.0.0"
typer = {extras = ["all"], version = "^0.12.5"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py312']
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.env
  | \.venv
)/
'''

[tool.isort]
profile = "black"
line_length = 120
known_third_party = ["meldingen_core"]
known_first_party = ["meldingen"]
overwrite_in_place = true

[tool.mypy]
plugins = [
  "pydantic.mypy"
]
strict = true

[tool.mypy-baseline]
baseline_path = "mypy-baseline.txt"

[tool.coverage.run]
concurrency = ["greenlet"]
omit = [
  "tests/*",
  "migrations/env.py",
  "meldingen/dependencies.py",
  "meldingen/database.py",
]
