[tool.poetry]
name = "meldingen"
version = "0.1.0"
description = "The main meldingen project which includes the framework bindings."
authors = [
  "Youri Westerman <y.westerman@amsterdam.nl>",
  "David van Buiten <d.van.buiten@amsterdam.nl>"
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
alembic = "^1.14.0"
alembic-postgresql-enum = "^1.4.0"
asgi-correlation-id = "^4.3.4"
asyncpg = "^0.30.0"
fastapi = {extras = ["standard"], version = "^0.115.5"}
geoalchemy2 = "^0.16.0"
geojson-pydantic = "^1.2.0"
httpx = {extras = ["http2"], version = "^0.28.1"}
maykin-json-logic-py = "^0.13.0"
meldingen-core = {git = "https://github.com/Amsterdam/meldingen-core.git", rev="36afaf4"}
mp-fsm = {git = "https://github.com/Amsterdam/mp-fsm.git"}
phonenumbers = "^8.13.52"
pydantic = {extras = ["email"], version = "^2.10.4"}
pydantic-extra-types = "^2.10.1"
pydantic-jsonlogic = {git = "https://github.com/Amsterdam/pydantic-jsonlogic.git"}
pydantic-media-type = {git = "https://github.com/Amsterdam/pydantic-media-type.git"}
pydantic-settings = "^2.7.0"
pyjwt = {extras = ["crypto"], version = "^2.10.1"}
python-magic = "^0.4.27"
python-multipart = "^0.0.20"
shapely = "^2.0.6"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.35"}
structlog = "^24.1.0"

[tool.poetry.group.dev.dependencies]
asgi-lifespan = "^2.1.0"
black = "^24.10.0"
isort = "^5.13.2"
mkdocs-literate-nav = "^0.6.1"
mkdocs-material = "^9.5.49"
mkdocstrings = {version = "^0.27.0", extras = ["python"]}
mypy = "^1.12.1"
mypy-baseline = "^0.7.1"
pre-commit = "^4.0.0"
pytest = "^8.3.3"
pytest-alembic = "^0.11.1"
pytest-cov = "^6.0.0"
typer = {extras = ["all"], version = "^0.15.1"}
types-shapely = "^2.0.0.20241221"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py312']
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.env
  | \.venv
)/
'''

[tool.isort]
profile = "black"
line_length = 120
known_third_party = ["meldingen_core"]
known_first_party = ["meldingen"]
overwrite_in_place = true

[tool.mypy]
plugins = [
  "pydantic.mypy"
]
strict = true

[tool.mypy-baseline]
baseline_path = "mypy-baseline.txt"

[tool.coverage.run]
concurrency = ["greenlet"]
omit = [
  "tests/*",
  "migrations/env.py",
  "meldingen/dependencies.py",
  "meldingen/database.py",
]
