[tool.poetry]
name = "meldingen"
version = "0.1.0"
description = "The main meldingen project which includes the framework bindings."
authors = [
  "Youri Westerman <y.westerman@amsterdam.nl>",
  "David van Buiten <d.van.buiten@amsterdam.nl>"
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.109.0"
uvicorn = {extras = ["standard"], version = "^0.27.0"}
pydantic-settings = "^2.1.0"
meldingen-core = {git = "https://github.com/Amsterdam/meldingen-core.git"}
sqlmodel = "^0.0.14"
psycopg2 = "^2.9.9"
alembic = "^1.13.1"
dependency-injector = {git = "https://github.com/anton-petrov/python-dependency-injector.git"}

[tool.poetry.group.dev.dependencies]
black = "^24.1.1"
isort = "^5.13.2"
mypy = "^1.8.0"
pytest = "^8.0.0"
pytest-alembic = "^0.10.7"
mkdocstrings = {version = "^0.24.0", extras = ["python"]}
mkdocs-material = "^9.5.6"
mkdocs-literate-nav = "^0.6.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py312']
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.env
  | \.venv
)/
'''

[tool.isort]
profile = "black"
line_length = 120
known_third_party = ["meldingen_core"]
known_first_party = ["meldingen"]

[tool.mypy]
plugins = [
  "pydantic.mypy"
]

[tool.mypy-baseline]
baseline_path = "mypy-baseline.txt"
