"""attachment optimized path

Revision ID: 02730cade609
Revises: f00d6c808e2d
Create Date: 2024-11-05 12:47:44.106776

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "02730cade609"
down_revision: str | None = "f00d6c808e2d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("attachment", sa.Column("optimized_path", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("attachment", "optimized_path")
    # ### end Alembic commands ###
