"""token

Revision ID: 0bdbf9571b2a
Revises: 1fae2f582091
Create Date: 2024-04-10 14:18:09.096404

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0bdbf9571b2a"
down_revision: str | None = "1fae2f582091"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("melding", sa.Column("token", sa.String(), nullable=True))
    op.add_column("melding", sa.Column("token_expires", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("melding", "token_expires")
    op.drop_column("melding", "token")
    # ### end Alembic commands ###
