"""add select component type to enum

Revision ID: 102eaa13b8d8
Revises: cd7033b17112
Create Date: 2024-07-31 14:55:15.907483

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "102eaa13b8d8"
down_revision: str | None = "cd7033b17112"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "form_io_component_type",
        ["panel", "text_area", "text_field", "checkbox", "radio", "select"],
        [
            TableReference(
                table_schema="public",
                table_name="form_io_component",
                column_name="type",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "form_io_component_type",
        ["panel", "text_area", "text_field", "checkbox", "radio"],
        [
            TableReference(
                table_schema="public",
                table_name="form_io_component",
                column_name="type",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
