"""add original question text column

Revision ID: 12443e52b756
Revises: 5d12506587d5
Create Date: 2026-02-25 12:44:38.124014

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "12443e52b756"
down_revision: str | None = "5d12506587d5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "answer",
        sa.Column("original_question_text", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("answer", "original_question_text")
    # ### end Alembic commands ###
