"""conditional column

Revision ID: 1516c4c88af8
Revises: 674ac6d290b0
Create Date: 2025-11-14 14:49:04.616526

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1516c4c88af8"
down_revision: str | None = "674ac6d290b0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("form_io_component", sa.Column("conditional", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("form_io_component", "conditional")
    # ### end Alembic commands ###
