"""attachment optimized path

Revision ID: 1dff133d9463
Revises: f00d6c808e2d
Create Date: 2024-11-05 13:02:52.904002

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1dff133d9463"
down_revision: str | None = "f00d6c808e2d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("attachment", sa.Column("optimized_path", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("attachment", "optimized_path")
    # ### end Alembic commands ###
