"""replace show_char_count with max_char_count

Revision ID: 1ee626c162c5
Revises: 8fccb0ff8cc7
Create Date: 2024-09-18 09:52:59.862052

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ee626c162c5"
down_revision: str | None = "8fccb0ff8cc7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "form_io_component",
        sa.Column("max_char_count", sa.Integer(), nullable=True),
    )
    op.drop_column("form_io_component", "show_char_count")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "form_io_component",
        sa.Column("show_char_count", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.drop_column("form_io_component", "max_char_count")
    # ### end Alembic commands ###
