"""asset

Revision ID: 2607118a0097
Revises: 304f00a0edb1
Create Date: 2025-06-30 12:43:11.770851

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2607118a0097"
down_revision: str | None = "304f00a0edb1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset_type",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "asset",
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["asset_type.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_table(
        "asset_melding",
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("melding_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["asset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["melding_id"],
            ["melding.id"],
        ),
        sa.PrimaryKeyConstraint("asset_id", "melding_id"),
    )
    op.add_column(
        "classification",
        sa.Column("asset_type_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key("classification_asset_type", "classification", "asset_type", ["asset_type_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("classification_asset_type", "classification", type_="foreignkey")
    op.drop_column("classification", "asset_type_id")
    op.drop_table("asset_melding")
    op.drop_table("asset")
    op.drop_table("asset_type")
    # ### end Alembic commands ###
