"""address info melding

Revision ID: 304f00a0edb1
Revises: da16ffde92e8
Create Date: 2025-05-06 12:47:59.334851

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "304f00a0edb1"
down_revision: str | None = "da16ffde92e8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("melding", sa.Column("street", sa.String(), nullable=True))
    op.add_column(
        "melding", sa.Column("house_number", sa.Integer(), nullable=True)
    )
    op.add_column(
        "melding",
        sa.Column("house_number_addition", sa.String(), nullable=True),
    )
    op.add_column(
        "melding",
        sa.Column("postal_code", sa.String(length=16), nullable=True),
    )
    op.add_column("melding", sa.Column("city", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("melding", "city")
    op.drop_column("melding", "postal_code")
    op.drop_column("melding", "house_number_addition")
    op.drop_column("melding", "house_number")
    op.drop_column("melding", "street")
    # ### end Alembic commands ###
