"""forms.io models

Revision ID: 30ba4ee50663
Revises: f9c612dd4b0b
Create Date: 2024-03-07 09:24:51.173176

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "30ba4ee50663"
down_revision: str | None = "f9c612dd4b0b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "forms_io_form",
        sa.Column(
            "display",
            sa.Enum("form", "wizard", "pdf", name="forms_io_form_display"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "forms_io_component",
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("input", sa.Boolean(), nullable=False),
        sa.Column("auto_expand", sa.Boolean(), nullable=False),
        sa.Column("show_char_count", sa.Boolean(), nullable=False),
        sa.Column("form_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["form_id"],
            ["forms_io_form.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("forms_io_component")
    op.drop_table("forms_io_form")
    # ### end Alembic commands ###

    sa.Enum("form", "wizard", "pdf", name="forms_io_form_display").drop(op.get_bind())
