"""thumbnail_path attachment

Revision ID: 3c9411e76910
Revises: 1dff133d9463
Create Date: 2024-11-11 12:40:21.651516

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3c9411e76910"
down_revision: str | None = "1dff133d9463"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("attachment", sa.Column("thumbnail_path", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("attachment", "thumbnail_path")
    # ### end Alembic commands ###
