"""Added created_at and updated_at fields

Revision ID: 458776297082
Revises: 5911ae2a50cb
Create Date: 2024-05-02 11:27:31.515576

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "458776297082"
down_revision: str | None = "5911ae2a50cb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("answer", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("answer", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.add_column(
        "classification",
        sa.Column("created_at", sa.DateTime(), nullable=False),
    )
    op.add_column(
        "classification",
        sa.Column("updated_at", sa.DateTime(), nullable=False),
    )
    op.add_column(
        "form_io_component",
        sa.Column("created_at", sa.DateTime(), nullable=False),
    )
    op.add_column(
        "form_io_component",
        sa.Column("updated_at", sa.DateTime(), nullable=False),
    )
    op.add_column("form_io_form", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("form_io_form", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.add_column("group", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("group", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.add_column("melding", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("melding", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.add_column("question", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("question", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.add_column("user", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("user", sa.Column("updated_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "updated_at")
    op.drop_column("user", "created_at")
    op.drop_column("question", "updated_at")
    op.drop_column("question", "created_at")
    op.drop_column("melding", "updated_at")
    op.drop_column("melding", "created_at")
    op.drop_column("group", "updated_at")
    op.drop_column("group", "created_at")
    op.drop_column("form_io_form", "updated_at")
    op.drop_column("form_io_form", "created_at")
    op.drop_column("form_io_component", "updated_at")
    op.drop_column("form_io_component", "created_at")
    op.drop_column("classification", "updated_at")
    op.drop_column("classification", "created_at")
    op.drop_column("answer", "updated_at")
    op.drop_column("answer", "created_at")
    # ### end Alembic commands ###
