"""melding phone and email

Revision ID: 534a016640f8
Revises: 6457634b25d9
Create Date: 2025-01-03 14:12:19.110033

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "534a016640f8"
down_revision: str | None = "6457634b25d9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "melding", sa.Column("email", sa.String(length=254), nullable=True)
    )
    op.add_column(
        "melding", sa.Column("phone", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("melding", "phone")
    op.drop_column("melding", "email")
    # ### end Alembic commands ###
