"""Added foreign key constraints to the Question and FormIoFormComponent models

Revision ID: 5911ae2a50cb
Revises: ced03ae5d296
Create Date: 2024-04-30 07:51:05.050673

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5911ae2a50cb"
down_revision: str | None = "ced03ae5d296"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "form_io_component",
        sa.Column("question_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        None,
        "form_io_component",
        "question",
        ["question_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("question", sa.Column("form_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None,
        "question",
        "form_io_form",
        ["form_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("question", "form_id")
    op.drop_column("form_io_component", "question_id")
    # ### end Alembic commands ###
