"""value and label answer

Revision ID: 5d12506587d5
Revises: fa34d0f248d8
Create Date: 2025-12-22 13:23:02.265728

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "5d12506587d5"
down_revision: str | None = "fa34d0f248d8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("answer", sa.Column("values_and_labels", sa.JSON(), nullable=True))
    op.sync_enum_values(
        enum_schema="public",
        enum_name="answer_type",
        new_values=["text", "time", "date", "value_label"],
        affected_columns=[TableReference(table_schema="public", table_name="answer", column_name="type")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="answer_type",
        new_values=["text", "time", "date"],
        affected_columns=[TableReference(table_schema="public", table_name="answer", column_name="type")],
        enum_values_to_rename=[],
    )
    op.drop_column("answer", "values_and_labels")
    # ### end Alembic commands ###
