"""formio panel component title

Revision ID: 6457634b25d9
Revises: a4c7c0e946d2
Create Date: 2024-12-09 12:35:49.579467

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6457634b25d9"
down_revision: str | None = "a4c7c0e946d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("form_io_component", sa.Column("title", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("form_io_component", "title")
    # ### end Alembic commands ###
