"""Add instruction field

Revision ID: 6523e6015f31
Revises: 7a9f5e2e9d1b
Create Date: 2026-03-17 09:49:30.854967

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6523e6015f31"
down_revision: str | None = "7a9f5e2e9d1b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "classification", sa.Column("instructions", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("classification", "instructions")
    # ### end Alembic commands ###
