"""set_max_assets_non_nullable

Revision ID: 674ac6d290b0
Revises: bb1a3057ffcd
Create Date: 2025-11-04 09:31:59.048327

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "674ac6d290b0"
down_revision: str | None = "bb1a3057ffcd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("asset_type", "max_assets", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("asset_type", "max_assets", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
