"""Add required field to form question component

Revision ID: 6b3db5c9e605
Revises: 1ee626c162c5
Create Date: 2024-09-25 12:40:39.821397

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6b3db5c9e605"
down_revision: str | None = "1ee626c162c5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("form_io_component", sa.Column("required", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("form_io_component", "required")
    # ### end Alembic commands ###
