"""melding labels

Revision ID: 6c2b254579da
Revises: 6523e6015f31
Create Date: 2026-04-20 14:47:32.701882

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6c2b254579da"
down_revision: str | None = "6523e6015f31"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "label",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "label_melding",
        sa.Column("label_id", sa.Integer(), nullable=False),
        sa.Column("melding_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["label_id"],
            ["label.id"],
        ),
        sa.ForeignKeyConstraint(
            ["melding_id"],
            ["melding.id"],
        ),
        sa.PrimaryKeyConstraint("label_id", "melding_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("label_melding")
    op.drop_table("label")
    # ### end Alembic commands ###
