"""time question component

Revision ID: 73c1a14b1f62
Revises: ca3e63fcdb25
Create Date: 2025-11-26 14:09:46.004893

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "73c1a14b1f62"
down_revision: str | None = "ca3e63fcdb25"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="form_io_component_type",
        new_values=[
            "panel",
            "text_area",
            "text_field",
            "checkbox",
            "radio",
            "select",
            "date",
            "time",
        ],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="form_io_component",
                column_name="type",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="form_io_component_type",
        new_values=[
            "panel",
            "text_area",
            "text_field",
            "checkbox",
            "radio",
            "select",
            "date",
        ],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="form_io_component",
                column_name="type",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
