"""add user to attachment column

Revision ID: 75ab04c1868a
Revises: c7a9d0f1e2b3
Create Date: 2026-07-31 12:05:28.890870

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "75ab04c1868a"
down_revision: str | None = "c7a9d0f1e2b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("attachment", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "attachment", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("attachment_user_id_fkey", "attachment", type_="foreignkey")
    op.drop_column("attachment", "user_id")
    # ### end Alembic commands ###
