"""Form models

Revision ID: 781aa6a913a6
Revises: 458776297082
Create Date: 2024-05-30 10:46:48.470103

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "781aa6a913a6"
down_revision: str | None = "458776297082"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "static_form",
        sa.Column("type", sa.Enum("primary", name="static_form_type"), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column(
            "display",
            sa.Enum("form", "wizard", "pdf", name="form_io_form_display"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("type"),
    )
    op.create_table(
        "form",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("classification_id", sa.Integer(), nullable=True),
        sa.Column(
            "display",
            sa.Enum("form", "wizard", "pdf", name="form_io_form_display"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["classification_id"],
            ["classification.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("classification_id"),
    )
    op.create_table(
        "form_io_component",
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "type",
            sa.Enum("panel", "text_area", "textfield", "selectboxes", "radio", name="form_io_component_type"),
            nullable=False,
        ),
        sa.Column("input", sa.Boolean(), nullable=False),
        sa.Column("auto_expand", sa.Boolean(), nullable=True),
        sa.Column("show_char_count", sa.Boolean(), nullable=True),
        sa.Column("form_id", sa.Integer(), nullable=True),
        sa.Column("static_form_id", sa.Integer(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("question_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "form_id IS NULL OR static_form_id IS NULL",
            name="only_form_or_static_form_constraint",
        ),
        sa.ForeignKeyConstraint(
            ["form_id"],
            ["form.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["form_io_component.id"],
        ),
        sa.ForeignKeyConstraint(["question_id"], ["question.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["static_form_id"],
            ["static_form.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("question", sa.Column("form_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "question", "form", ["form_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("question", "form_id")
    op.drop_table("form_io_component")
    op.drop_table("form")
    op.drop_table("static_form")
    # ### end Alembic commands ###

    sa.Enum("form", "wizard", "pdf", name="form_io_form_display").drop(op.get_bind())
    sa.Enum("panel", "text_area", "textfield", "selectboxes", "radio", name="form_io_component_type").drop(
        op.get_bind()
    )
    sa.Enum("primary", name="static_form_type").drop(op.get_bind())
