"""attachment media type fields

Revision ID: 787eaeac6380
Revises: f88c971186dc
Create Date: 2025-04-14 13:06:07.163203

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "787eaeac6380"
down_revision: str | None = "f88c971186dc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "attachment",
        sa.Column("original_media_type", sa.String(), nullable=False),
    )
    op.add_column(
        "attachment",
        sa.Column("optimized_media_type", sa.String(), nullable=True),
    )
    op.add_column(
        "attachment",
        sa.Column("thumbnail_media_type", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("attachment", "thumbnail_media_type")
    op.drop_column("attachment", "optimized_media_type")
    op.drop_column("attachment", "original_media_type")
    # ### end Alembic commands ###
