"""text answer from

Revision ID: 891e9506cd80
Revises: 73c1a14b1f62
Create Date: 2025-11-28 14:24:14.089898

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "891e9506cd80"
down_revision: str | None = "73c1a14b1f62"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("text", name="answer_type").create(op.get_bind())
    op.add_column(
        "answer",
        sa.Column(
            "type",
            postgresql.ENUM("text", name="answer_type", create_type=False),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("answer", "type")
    sa.Enum("text", name="answer_type").drop(op.get_bind())
    # ### end Alembic commands ###
