"""add answer snapshot fields

Revision ID: 8a68db304e9e
Revises: a1b2c3d4e5f6
Create Date: 2026-05-21 16:03:51.801721

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8a68db304e9e"
down_revision: str | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("answer", sa.Column("component_position", sa.Integer(), nullable=True))
    op.add_column("answer", sa.Column("panel_position", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("answer", "panel_position")
    op.drop_column("answer", "component_position")
    # ### end Alembic commands ###
