"""jsonlogic column

Revision ID: 8fccb0ff8cc7
Revises: dcd6917ded7d
Create Date: 2024-09-11 09:49:41.038811

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8fccb0ff8cc7"
down_revision: str | None = "dcd6917ded7d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("form_io_component", sa.Column("jsonlogic", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("form_io_component", "jsonlogic")
    # ### end Alembic commands ###
