"""geolocation column

Revision ID: a4c7c0e946d2
Revises: 3c9411e76910
Create Date: 2024-11-15 10:14:59.601916

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = "a4c7c0e946d2"
down_revision: str | None = "3c9411e76910"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_geospatial_column(
        "melding",
        sa.Column(
            "geo_location",
            Geometry(
                srid=4326,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
    )
    op.create_geospatial_index(
        "idx_melding_geo_location",
        "melding",
        ["geo_location"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index(
        "idx_melding_geo_location",
        table_name="melding",
        postgresql_using="gist",
        column_name="geo_location",
    )
    op.drop_geospatial_column("melding", "geo_location")
    # ### end Alembic commands ###
