"""melding state

Revision ID: b3425e4102aa
Revises: f9c612dd4b0b
Create Date: 2024-03-12 14:07:29.275425

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b3425e4102aa"
down_revision: str | None = "f9c612dd4b0b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("melding", sa.Column("state", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("melding", "state")
    # ### end Alembic commands ###
