"""add max_assets field to asset_type model

Revision ID: bb1a3057ffcd
Revises: c5fa7f605c3c
Create Date: 2025-10-27 10:47:10.606219

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bb1a3057ffcd"
down_revision: str | None = "c5fa7f605c3c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("asset_type", sa.Column("max_assets", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("asset_type", "max_assets")
    # ### end Alembic commands ###
