"""Form io models

Revision ID: c2c58caf1352
Revises: b3425e4102aa
Create Date: 2024-03-13 13:48:59.272869

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c2c58caf1352"
down_revision: str | None = "b3425e4102aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "form_io_form",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column(
            "display",
            sa.Enum("form", "wizard", "pdf", name="form_io_form_display"),
            nullable=False,
        ),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "form_io_component",
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("panel", "text_area", name="form_io_component_type"),
            nullable=False,
        ),
        sa.Column("input", sa.Boolean(), nullable=False),
        sa.Column("auto_expand", sa.Boolean(), nullable=False),
        sa.Column("show_char_count", sa.Boolean(), nullable=False),
        sa.Column("form_id", sa.Integer(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["form_id"],
            ["form_io_form.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["form_io_component.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("form_io_component")
    op.drop_table("form_io_form")
    # ### end Alembic commands ###

    sa.Enum("form", "wizard", "pdf", name="form_io_form_display").drop(op.get_bind())
    sa.Enum("panel", "text_area", name="form_io_component_type").drop(op.get_bind())
