"""added zip code and address to melding

Revision ID: c39a4af13e4b
Revises: da16ffde92e8
Create Date: 2025-05-06 08:50:53.986135

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c39a4af13e4b"
down_revision: str | None = "da16ffde92e8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("melding", sa.Column("address", sa.String(), nullable=True))
    op.add_column(
        "melding", sa.Column("zip_code", sa.String(length=16), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("melding", "zip_code")
    op.drop_column("melding", "address")
    # ### end Alembic commands ###
