"""add tables for select form component

Revision ID: c45b8194f6bc
Revises: 102eaa13b8d8
Create Date: 2024-08-01 11:19:55.760051

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c45b8194f6bc"
down_revision: str | None = "102eaa13b8d8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "form_io_select_component_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "form_io_select_component_value",
        sa.Column("data_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["data_id"],
            ["form_io_select_component_data.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("form_io_component", sa.Column("data_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("form_io_component", "data_id")
    op.drop_table("form_io_select_component_value")
    op.drop_table("form_io_select_component_data")
    # ### end Alembic commands ###
