"""add user column to attachment

Revision ID: c6b5bcde3f00
Revises: b7e2c9a1f4d3
Create Date: 2026-07-28 09:07:08.062207

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c6b5bcde3f00"
down_revision: str | None = "b7e2c9a1f4d3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("attachment", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key("attachment_user_id_fkey", "attachment", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("attachment_user_id_fkey", "attachment", type_="foreignkey")
    op.drop_column("attachment", "user_id")
    # ### end Alembic commands ###
