"""casbin rule

Revision ID: c6f9ab9ddb43
Revises: 696f35b71c7e
Create Date: 2024-02-16 09:51:12.945360

"""

from typing import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c6f9ab9ddb43"
down_revision: str | None = "696f35b71c7e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "casbin_rule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ptype", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("v0", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("v1", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("v2", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("v3", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("v4", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("v5", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("casbin_rule")
    # ### end Alembic commands ###
