"""asset_type_class

Revision ID: c7d51956c500
Revises: 2607118a0097
Create Date: 2025-06-30 13:57:06.863617

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7d51956c500"
down_revision: str | None = "2607118a0097"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("asset_type", sa.Column("class_name", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("asset_type", "class_name")
    # ### end Alembic commands ###
