"""external_id and type_id unique

Revision ID: c8c2fdecdd9a
Revises: e7b1791e9351
Create Date: 2025-07-10 06:43:10.901267

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8c2fdecdd9a"
down_revision: str | None = "e7b1791e9351"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("asset_external_id_key"), "asset", type_="unique")
    op.create_unique_constraint("asset_external_id_type_id_unique", "asset", ["external_id", "type_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("asset_external_id_type_id_unique", "asset", type_="unique")
    op.create_unique_constraint(
        op.f("asset_external_id_key"),
        "asset",
        ["external_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
