"""date question component

Revision ID: ca3e63fcdb25
Revises: 1516c4c88af8
Create Date: 2025-11-24 15:28:08.325188

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "ca3e63fcdb25"
down_revision: str | None = "1516c4c88af8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "form_io_component",
        sa.Column("day_range", sa.Integer(), nullable=True),
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="form_io_component_type",
        new_values=[
            "panel",
            "text_area",
            "text_field",
            "checkbox",
            "radio",
            "select",
            "date",
        ],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="form_io_component",
                column_name="type",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="form_io_component_type",
        new_values=[
            "panel",
            "text_area",
            "text_field",
            "checkbox",
            "radio",
            "select",
        ],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="form_io_component",
                column_name="type",
            )
        ],
        enum_values_to_rename=[],
    )
    op.drop_column("form_io_component", "day_range")
    # ### end Alembic commands ###
