"""update form component types enum

Revision ID: cd7033b17112
Revises: d52cddd07abd
Create Date: 2024-07-31 13:32:25.035175

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "cd7033b17112"
down_revision: str | None = "d52cddd07abd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "form_io_component_type",
        ["panel", "text_area", "text_field", "checkbox", "radio"],
        [
            TableReference(
                table_schema="public",
                table_name="form_io_component",
                column_name="type",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "form_io_component_type",
        ["panel", "text_area", "textfield", "selectboxes", "radio"],
        [
            TableReference(
                table_schema="public",
                table_name="form_io_component",
                column_name="type",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
