"""form classification

Revision ID: ced03ae5d296
Revises: 0bdbf9571b2a
Create Date: 2024-04-16 10:18:22.747064

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ced03ae5d296"
down_revision: str | None = "0bdbf9571b2a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "form_io_form",
        sa.Column("classification_id", sa.Integer(), nullable=True),
    )
    op.create_unique_constraint("form_io_form_classification_id_key", "form_io_form", ["classification_id"])
    op.create_foreign_key(
        "form_io_form_classification_id_fkey", "form_io_form", "classification", ["classification_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("form_io_form_classification_id_fkey", "form_io_form", type_="foreignkey")
    op.drop_constraint("form_io_form_classification_id_key", "form_io_form", type_="unique")
    op.drop_column("form_io_form", "classification_id")
    # ### end Alembic commands ###
