"""attachment optimized

Revision ID: d11f1a8d06d6
Revises: f00d6c808e2d
Create Date: 2024-10-29 13:07:03.078189

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d11f1a8d06d6"
down_revision: str | None = "f00d6c808e2d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("attachment", sa.Column("optimized", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("attachment", "optimized")
    # ### end Alembic commands ###
