"""empty message

Revision ID: d52cddd07abd
Revises: 633744d2ba79
Create Date: 2024-07-09 07:49:53.279452

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d52cddd07abd"
down_revision: str | None = "633744d2ba79"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_attachment_unique_identifier", table_name="attachment")
    op.drop_column("attachment", "unique_identifier")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "attachment",
        sa.Column("unique_identifier", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_index(
        "ix_attachment_unique_identifier",
        "attachment",
        ["unique_identifier"],
        unique=True,
    )
    # ### end Alembic commands ###
