"""melding public id

Revision ID: da16ffde92e8
Revises: 787eaeac6380
Create Date: 2025-04-28 13:25:34.762248

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da16ffde92e8"
down_revision: str | None = "787eaeac6380"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("melding", sa.Column("public_id", sa.String(), nullable=False))
    op.create_unique_constraint("melding_public_id", "melding", ["public_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("melding_public_id", "melding", type_="unique")
    op.drop_column("melding", "public_id")
    # ### end Alembic commands ###
