"""widget and placeholder fields

Revision ID: dcd6917ded7d
Revises: 5d015538e015
Create Date: 2024-08-12 15:07:03.724120

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dcd6917ded7d"
down_revision: str | None = "5d015538e015"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("form_io_component", sa.Column("widget", sa.String(), nullable=True))
    op.add_column(
        "form_io_component",
        sa.Column("placeholder", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("form_io_component", "placeholder")
    op.drop_column("form_io_component", "widget")
    # ### end Alembic commands ###
