"""add service level objective props

Revision ID: e6d54c174dc2
Revises: a002f8e0b567
Create Date: 2026-09-23 12:36:58.454804

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e6d54c174dc2"
down_revision: str | None = "a002f8e0b567"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("working_days", "calendar_days", name="service_level_objective_day_type").create(op.get_bind())
    op.add_column(
        "classification", sa.Column("service_level_objective_text", sa.String(), server_default="-", nullable=False)
    )
    op.add_column(
        "classification", sa.Column("service_level_objective_days", sa.Integer(), server_default="5", nullable=False)
    )
    op.add_column(
        "classification",
        sa.Column(
            "service_level_objective_day_type",
            postgresql.ENUM(
                "working_days", "calendar_days", name="service_level_objective_day_type", create_type=False
            ),
            server_default="calendar_days",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("classification", "service_level_objective_day_type")
    op.drop_column("classification", "service_level_objective_days")
    op.drop_column("classification", "service_level_objective_text")
    sa.Enum("working_days", "calendar_days", name="service_level_objective_day_type").drop(op.get_bind())
    # ### end Alembic commands ###
