"""asset type arguments

Revision ID: e7b1791e9351
Revises: c7d51956c500
Create Date: 2025-07-02 07:58:25.783611

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7b1791e9351"
down_revision: str | None = "c7d51956c500"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("asset_type", sa.Column("arguments", sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("asset_type", "arguments")
    # ### end Alembic commands ###
