"""add time answer

Revision ID: eb1f60f8afbd
Revises: 891e9506cd80
Create Date: 2025-12-02 12:49:51.692286

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "eb1f60f8afbd"
down_revision: str | None = "891e9506cd80"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("answer", sa.Column("time", sa.String(), nullable=True))
    op.alter_column("answer", "text", existing_type=sa.VARCHAR(), nullable=True)
    op.sync_enum_values(
        enum_schema="public",
        enum_name="answer_type",
        new_values=["text", "time"],
        affected_columns=[TableReference(table_schema="public", table_name="answer", column_name="type")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="answer_type",
        new_values=["text"],
        affected_columns=[TableReference(table_schema="public", table_name="answer", column_name="type")],
        enum_values_to_rename=[],
    )
    op.alter_column("answer", "text", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("answer", "time")
    # ### end Alembic commands ###
