"""melding classification

Revision ID: ee7c68cb5efc
Revises: 696f35b71c7e
Create Date: 2024-02-21 15:50:25.774558

"""

from typing import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee7c68cb5efc"
down_revision: str | None = "696f35b71c7e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "classification",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("melding", sa.Column("classification_id", sa.Integer(), nullable=True))
    op.create_foreign_key("melding_classification", "melding", "classification", ["classification_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("melding_classification", "melding", type_="foreignkey")
    op.drop_column("melding", "classification_id")
    op.drop_table("classification")
    # ### end Alembic commands ###
