"""add other static form_types

Revision ID: f00d6c808e2d
Revises: 6b3db5c9e605
Create Date: 2024-10-22 08:50:03.602841

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "f00d6c808e2d"
down_revision: str | None = "6b3db5c9e605"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "static_form_type",
        ["primary", "attachments", "location", "contact"],
        [
            TableReference(
                table_schema="public",
                table_name="static_form",
                column_name="type",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "static_form_type",
        ["primary"],
        [
            TableReference(
                table_schema="public",
                table_name="static_form",
                column_name="type",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
