"""casbin rule

Revision ID: f213f7605809
Revises: a5699de7ffde
Create Date: 2024-02-14 12:18:52.281436

"""

from typing import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f213f7605809"
down_revision: str | None = "a5699de7ffde"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "casbin_rule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ptype", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("v0", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("v1", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("v2", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("v3", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("v4", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("v5", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("casbin_rule")
    # ### end Alembic commands ###
