"""remove location form type from enum

Revision ID: f88c971186dc
Revises: 534a016640f8
Create Date: 2025-02-18 09:48:05.391019

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "f88c971186dc"
down_revision: str | None = "534a016640f8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="static_form_type",
        new_values=["primary", "attachments", "contact"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="static_form",
                column_name="type",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="static_form_type",
        new_values=["primary", "attachments", "location", "contact"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="static_form",
                column_name="type",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
