"""classification name

Revision ID: f9c612dd4b0b
Revises: 4e605f652d66
Create Date: 2024-02-28 10:17:32.758465

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f9c612dd4b0b"
down_revision: str | None = "4e605f652d66"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("classification", sa.Column("name", sa.String(), nullable=False))
    op.create_unique_constraint("classification_name", "classification", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("classification_name", "classification", type_="unique")
    op.drop_column("classification", "name")
    # ### end Alembic commands ###
