"""date answer

Revision ID: fa34d0f248d8
Revises: eb1f60f8afbd
Create Date: 2025-12-19 14:02:22.826682

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "fa34d0f248d8"
down_revision: str | None = "eb1f60f8afbd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("answer", sa.Column("date", sa.JSON(), nullable=True))
    op.sync_enum_values(
        enum_schema="public",
        enum_name="answer_type",
        new_values=["text", "time", "date"],
        affected_columns=[TableReference(table_schema="public", table_name="answer", column_name="type")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="answer_type",
        new_values=["text", "time"],
        affected_columns=[TableReference(table_schema="public", table_name="answer", column_name="type")],
        enum_values_to_rename=[],
    )
    op.drop_column("answer", "date")
    # ### end Alembic commands ###
