"""add icon_path to asset type

Revision ID: fb0e206f1573
Revises: 674ac6d290b0
Create Date: 2025-11-10 13:31:56.418521

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb0e206f1573"
down_revision: str | None = "674ac6d290b0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Includes a temp fix to avoid issues with existing rows
    op.add_column("asset_type", sa.Column("icon_path", sa.String(), nullable=False, server_default="temp"))
    op.alter_column("asset_type", "icon_path", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("asset_type", "icon_path")
    # ### end Alembic commands ###
