receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  azuremonitor:
    spaneventsenabled: true

processors:
  batch:

service:
  telemetry:
    logs:
      level: DEBUG
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [azuremonitor]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [azuremonitor]
