name: Build
on: [pull_request]
permissions:
  contents: read
  packages: write

jobs:
  build_container_images:
    runs-on:
      group: large-runners
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create the .env file
        run: cp .env.example .env

      - name: Build containers
        run: docker buildx bake --file docker-compose.yml --file docker-compose.cache.json
