name: Tests
on:
  workflow_run:
    workflows: [Build]
    types: [completed]
permissions:
  contents: read
  packages: write
jobs:
  run_tests:
    runs-on:
      group: large-runners
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull container images
        run: |
          docker compose --file docker-compose.yml --file docker-compose.cache.json pull meldingen

      - name: Create the .env file
        run: cp .env.example .env

      - name: Run alembic tests
        run: docker compose run --rm meldingen pytest --test-alembic -m alembic

      - name: Run tests
        run: docker compose run --rm -e COVERAGE_FILE=/tmp/.coverage meldingen pytest --cov --cov-fail-under=95 -n auto -v
