name: Tests
on: [pull_request]
permissions:
  contents: read
  packages: write

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create the .env file
        run: cp .env.example .env

      - name: Build containers
        run: docker buildx bake --file docker-compose.yml --file docker-compose.cache.json

      - name: Run tests
        run: API_DATABASE_DSN="postgresql+asyncpg://meldingen:postgres@database:5432/meldingen-test" docker compose run -e DATABASE_DSN --rm meldingen pytest --test-alembic  --cov --cov-fail-under=97 -v
