name: Tests
on: [pull_request]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start containers
        run: docker-compose build

      - name: Test migrations
        run: docker-compose run --rm meldingen pytest --test-alembic -v -m "alembic"

      - name: Run tests
        run: docker-compose run --rm meldingen pytest -v
